[2024-02-18 13:04:59 +0530] [24994] [INFO] Starting gunicorn 21.2.0
[2024-02-18 13:04:59 +0530] [24994] [INFO] Listening at: unix:/home/eleensmathew/gunicorn.sock (24994)
[2024-02-18 13:04:59 +0530] [24994] [INFO] Using worker: sync
[2024-02-18 13:04:59 +0530] [24998] [INFO] Booting worker with pid: 24998
[2024-02-18 13:04:59 +0530] [24998] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/eleensmathew/news/env/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/eleensmathew/news/env/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/eleensmathew/news/env/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/eleensmathew/news/env/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/eleensmathew/news/env/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/eleensmathew/news/env/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/eleensmathew/news/env/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mysite.wsgi'
[2024-02-18 13:04:59 +0530] [24998] [INFO] Worker exiting (pid: 24998)
[2024-02-18 13:04:59 +0530] [24994] [ERROR] Worker (pid:24998) exited with code 3
[2024-02-18 13:04:59 +0530] [24994] [ERROR] Shutting down: Master
[2024-02-18 13:04:59 +0530] [24994] [ERROR] Reason: Worker failed to boot.
